baseURL = "https://buffos.github.io"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
# website title
title = "DoIt"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true

# ignore some build errors
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# theme
theme = "DoIt"
# themes directory
# themesDir = "../.."

# Or, when using theme as hugo module
# [module]
# [[module.imports]]
# path = "github.com/HEIGE-PCloud/DoIt"
